"""add Google login fields

Revision ID: 107c6cd51912
Revises: ac2132a099f3
Create Date: 2025-08-24 00:23:34.078652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107c6cd51912'
down_revision = 'ac2132a099f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('oauth_provider')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
